# Generated by Django 5.1.2 on 2024-10-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deck", models.JSONField()),
                ("player_hand", models.JSONField(default=list)),
                ("dealer_hand", models.JSONField(default=list)),
                ("player_score", models.IntegerField(default=0)),
                ("dealer_score", models.IntegerField(default=0)),
                ("player_chips", models.JSONField(default=list)),
                ("player_chips_v", models.IntegerField(default=500)),
                ("dealer_chips", models.JSONField(default=list)),
                ("dealer_chips_v", models.IntegerField(default=500)),
                ("player_bet", models.IntegerField(default=0)),
                ("dealer_bet", models.IntegerField(default=0)),
                ("round_bet", models.IntegerField(default=0)),
                ("game_result", models.CharField(default="", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
