# Generated by Django 5.1.2 on 2024-11-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_game_dealer_bet_v_game_player_bet_v_game_round_bet_v"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="dealer_bet",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="dealer_bet_v",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_bet",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_bet_v",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="round_bet",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="round_bet_v",
            field=models.IntegerField(default=0),
        ),
    ]
