# Generated by Django 5.1.2 on 2024-10-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="dealer_bet_v",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="player_bet_v",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="round_bet_v",
            field=models.JSONField(default=list),
        ),
    ]
